export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST'
export const LOAD_PRODUCTS_RESPONSE = 'LOAD_PRODUCTS_RESPONSE'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const UPDATE_CHART_BOUND = 'UPDATE_CHART_BOUND'
